#!/bin/sh

xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V

bspc config border_width 2
bspc config focused_border_color "#585B70"
bspc config normal_border_color "#45475A"
bspc config window_gap 5
bspc config split_ratio 0.618

feh --bg-fill --randomize "$HOME/wallpapers"
sxhkd &
picom &
